# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

i_am_a_sponsor: true
appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo blog theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '<i class="far fa-copyright"></i> 2016-{year} 孙子平&韦婷 [京ICP备 17062397号-2](https://beian.miit.gov.cn)'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2006年1月2日'
  time_format: '15:04'
  address_format: zh

plugins_js: ['cross-reference', 'fix-search-common']

# Site features

features:
  syntax_highlighter:
    enable: true
    theme_light: xcode-light
    theme_dark: xcode-dark
  math:
    enable: true
  diagram:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/sunziping2016/blog'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'commento'
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: 'https://commento.szp15.com'
  search:
    provider: algolia
    algolia:
      app_id: '6ATAB1HBV6'
      api_key: 'd18c880fa171aef8cb0844ddf1e269cd'
      index_name: 'szp15.com'
      show_logo: true
  map:
    provider: ''
    api_key: ''
    zoom: 15

marketing:
  analytics:
    google_analytics: 'UA-88008647-1'
    microsoft_clarity: '8rvhp8928v'

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
