name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16.x]

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
        extended: true

    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Install dependencies
      run: npm install

    - name: Check for linting errors
      run: npm test

    - name: Build production website
      run: hugo -D

    - name: Deploy to szp15.com
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == '16.x' }}
      run: rsync -avz --delete public/ sun@szp15.com:/srv/http/blog/
